#!/usr/bin/env bash
set -euo pipefail

# Fairtrail — One-command setup
# Detects Claude Code / Codex CLI for zero-API-key setup,
# or prompts for a key if neither is found.

BOLD='\033[1m'
DIM='\033[2m'
CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
RESET='\033[0m'

info()  { echo -e "${CYAN}${BOLD}▸${RESET} $1"; }
ok()    { echo -e "${GREEN}${BOLD}✓${RESET} $1"; }
warn()  { echo -e "${YELLOW}${BOLD}!${RESET} $1"; }
fail()  { echo -e "${RED}${BOLD}✗${RESET} $1"; exit 1; }

echo ""
echo -e "${BOLD}  Fairtrail — Flight Price Tracker${RESET}"
echo -e "  ${DIM}The price trail airlines don't show you${RESET}"
echo ""

# ---------------------------------------------------------------------------
# 1. Check Docker
# ---------------------------------------------------------------------------
if ! command -v docker &>/dev/null; then
  fail "Docker Desktop is required. Install from https://docs.docker.com/get-docker/"
fi

if ! docker info &>/dev/null 2>&1; then
  fail "Docker Desktop is not running. Start it and try again."
fi

ok "Ready"

# ---------------------------------------------------------------------------
# 2. Detect LLM providers (Claude Code CLI → Codex CLI → API key prompt)
# ---------------------------------------------------------------------------
CLAUDE_CODE_DETECTED=false
CODEX_DETECTED=false
API_KEY_VAR=""
API_KEY_VAL=""

# Check for Claude Code CLI
if command -v claude &>/dev/null && [ -d "$HOME/.claude" ]; then
  CLAUDE_CODE_DETECTED=true
  ok "Claude Code CLI detected — no API key needed"
fi

# Check for Codex CLI
if command -v codex &>/dev/null && [ -d "$HOME/.codex" ]; then
  CODEX_DETECTED=true
  ok "Codex CLI detected — no API key needed"
fi

# If no CLI found, prompt for API key
if [ "$CLAUDE_CODE_DETECTED" = false ] && [ "$CODEX_DETECTED" = false ]; then
  warn "No Claude Code or Codex CLI found"
  echo ""
  echo -e "  Paste an API key from any provider:"
  echo -e "  ${DIM}1. Anthropic  — https://console.anthropic.com/${RESET}"
  echo -e "  ${DIM}2. OpenAI     — https://platform.openai.com/api-keys${RESET}"
  echo -e "  ${DIM}3. Google AI  — https://aistudio.google.com/apikey${RESET}"
  echo ""
  read -rsp "  API key: " API_KEY_VAL
  echo ""

  if [ -z "$API_KEY_VAL" ]; then
    fail "No API key provided. Install Claude Code (https://docs.anthropic.com/en/docs/claude-code) or provide an API key."
  fi

  # Auto-detect provider from key prefix
  if [[ "$API_KEY_VAL" == sk-ant-* ]]; then
    API_KEY_VAR="ANTHROPIC_API_KEY"
    ok "Detected Anthropic key"
  elif [[ "$API_KEY_VAL" == sk-* ]]; then
    API_KEY_VAR="OPENAI_API_KEY"
    ok "Detected OpenAI key"
  elif [[ "$API_KEY_VAL" == AI* ]]; then
    API_KEY_VAR="GOOGLE_AI_API_KEY"
    ok "Detected Google AI key"
  else
    # Can't auto-detect — ask
    echo ""
    echo "  Which provider is this key for?"
    echo "  1) Anthropic"
    echo "  2) OpenAI"
    echo "  3) Google AI"
    read -rp "  Choice [1-3]: " PROVIDER_CHOICE
    case "$PROVIDER_CHOICE" in
      1) API_KEY_VAR="ANTHROPIC_API_KEY" ;;
      2) API_KEY_VAR="OPENAI_API_KEY" ;;
      3) API_KEY_VAR="GOOGLE_AI_API_KEY" ;;
      *) fail "Invalid choice" ;;
    esac
    ok "Using ${API_KEY_VAR}"
  fi
fi

# ---------------------------------------------------------------------------
# 3. Generate .env
# ---------------------------------------------------------------------------
generate_secret() {
  head -c 32 /dev/urandom | xxd -p | tr -d '\n' | head -c 32
}

ADMIN_PW=$(generate_secret | head -c 16)
SESSION_SECRET=$(generate_secret)
CRON_SECRET=$(generate_secret)

if [ -f .env ]; then
  warn "Existing .env found — backing up to .env.backup"
  cp .env .env.backup
fi

{
  echo "# Generated by setup.sh — $(date -u '+%Y-%m-%d %H:%M UTC')"
  echo "POSTGRES_PASSWORD=postgres"
  echo ""
  echo "# Admin"
  echo "ADMIN_PASSWORD=${ADMIN_PW}"
  echo "ADMIN_SESSION_SECRET=${SESSION_SECRET}"
  echo "CRON_SECRET=${CRON_SECRET}"

  # LLM provider
  echo ""
  if [ "$CLAUDE_CODE_DETECTED" = true ]; then
    echo "# Using Claude Code CLI (your existing subscription)"
    echo "CLAUDE_CODE_ENABLED=true"
  fi
  if [ "$CODEX_DETECTED" = true ]; then
    echo "# Using Codex CLI (your existing subscription)"
    echo "CODEX_ENABLED=true"
  fi
  if [ -n "$API_KEY_VAR" ]; then
    echo "${API_KEY_VAR}=${API_KEY_VAL}"
  fi
} > .env

ok "Generated .env"

# ---------------------------------------------------------------------------
# 4. Generate docker-compose.override.yml for CLI volume mounts
# ---------------------------------------------------------------------------
NEED_OVERRIDE=false
OVERRIDE_VOLUMES=""

if [ "$CLAUDE_CODE_DETECTED" = true ]; then
  NEED_OVERRIDE=true
  OVERRIDE_VOLUMES="${OVERRIDE_VOLUMES}
      - ${HOME}/.claude:/home/node/.claude:ro"
fi

if [ "$CODEX_DETECTED" = true ]; then
  NEED_OVERRIDE=true
  OVERRIDE_VOLUMES="${OVERRIDE_VOLUMES}
      - ${HOME}/.codex:/home/node/.codex:ro"
fi

if [ "$NEED_OVERRIDE" = true ]; then
  cat > docker-compose.override.yml << YAML
# Auto-generated by setup.sh — mounts CLI auth into the container
services:
  web:
    volumes:${OVERRIDE_VOLUMES}
YAML
  ok "Generated docker-compose.override.yml (CLI mounts)"
else
  # Remove stale override if it exists
  rm -f docker-compose.override.yml
fi

# ---------------------------------------------------------------------------
# 5. Install the `fairtrail` command
# ---------------------------------------------------------------------------
INSTALL_BIN="$HOME/.local/bin"
mkdir -p "$INSTALL_BIN"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ln -sf "$SCRIPT_DIR/bin/fairtrail" "$INSTALL_BIN/fairtrail"

# Check if ~/.local/bin is in PATH
if ! echo "$PATH" | tr ':' '\n' | grep -qx "$INSTALL_BIN"; then
  warn "$INSTALL_BIN is not in your PATH"
  echo ""
  echo -e "  Add this to your shell profile (~/.bashrc, ~/.zshrc, etc.):"
  echo -e "  ${BOLD}export PATH=\"\$HOME/.local/bin:\$PATH\"${RESET}"
  echo ""
fi

ok "Installed 'fairtrail' command to $INSTALL_BIN/fairtrail"

# ---------------------------------------------------------------------------
# 6. Start services
# ---------------------------------------------------------------------------
info "Starting Fairtrail (first run takes a minute)..."
echo ""

docker compose up -d --build 2>&1 | while IFS= read -r line; do
  echo -e "  ${DIM}${line}${RESET}"
done

echo ""

# ---------------------------------------------------------------------------
# 7. Wait for the app to be ready
# ---------------------------------------------------------------------------
info "Waiting for the app to start..."

PORT="${PORT:-3003}"
RETRIES=60
until curl -sf "http://localhost:${PORT}/api/health" >/dev/null 2>&1; do
  RETRIES=$((RETRIES - 1))
  if [ "$RETRIES" -le 0 ]; then
    warn "App didn't respond in 60s — run 'fairtrail logs' to debug"
    break
  fi
  sleep 1
done

if [ "$RETRIES" -gt 0 ]; then
  ok "Fairtrail is running"
fi

# ---------------------------------------------------------------------------
# 8. Print summary
# ---------------------------------------------------------------------------
echo ""
echo -e "${BOLD}  ┌──────────────────────────────────────────────────┐${RESET}"
echo -e "${BOLD}  │                                                  │${RESET}"
echo -e "${BOLD}  │${RESET}   ${CYAN}Fairtrail is ready${RESET}                            ${BOLD}│${RESET}"
echo -e "${BOLD}  │${RESET}                                                  ${BOLD}│${RESET}"
echo -e "${BOLD}  │${RESET}   Open:  ${BOLD}http://localhost:${PORT}${RESET}                  ${BOLD}│${RESET}"
echo -e "${BOLD}  │${RESET}                                                  ${BOLD}│${RESET}"

if [ "$CLAUDE_CODE_DETECTED" = true ] || [ "$CODEX_DETECTED" = true ]; then
  echo -e "${BOLD}  │${RESET}   LLM:   ${GREEN}Using your existing CLI subscription${RESET}  ${BOLD}│${RESET}"
else
  echo -e "${BOLD}  │${RESET}   LLM:   API key configured                     ${BOLD}│${RESET}"
fi

echo -e "${BOLD}  │${RESET}   Admin: password is in .env                     ${BOLD}│${RESET}"
echo -e "${BOLD}  │${RESET}                                                  ${BOLD}│${RESET}"
echo -e "${BOLD}  └──────────────────────────────────────────────────┘${RESET}"
echo ""
echo -e "  ${DIM}Complete setup at http://localhost:${PORT}/setup${RESET}"
echo ""
echo -e "  Next time, just run: ${BOLD}fairtrail${RESET}"
echo -e "  ${DIM}Ctrl+C to stop  |  fairtrail stop  |  fairtrail help${RESET}"
echo ""
